server:
  port: 8080

spring:
  profiles:
    active: dev

  main:
    allow-circular-references: true

  datasource:
    driver-class-name: ${device.datasource.driver-class-name}
    url: jdbc:mysql://${device.datasource.host}:${device.datasource.port}/${device.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${device.datasource.username}
    password: ${device.datasource.password}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaozhang.devicemanagesystem.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL到控制台

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

device:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: xiaozhang
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    token-name: token
